/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('./src/components/input/a-input.vue')['default']
    Beian: typeof import('./src/components/beian/beian.vue')['default']
    BInput: typeof import('./src/components/input/b-input.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    FullPage: typeof import('./src/components/interaction/fullpage/full-page.vue')['default']
    FullPageItem: typeof import('./src/components/interaction/fullpage/full-page-item.vue')['default']
    LogoIcon: typeof import('./src/components/logo/logo-icon.vue')['default']
    LogoIconName: typeof import('./src/components/logo/logo-icon-name.vue')['default']
    LogoName: typeof import('./src/components/logo/logo-name.vue')['default']
    OptionBlock: typeof import('./src/components/interaction/option/option-block.vue')['default']
    OptionInline: typeof import('./src/components/interaction/option/option-inline.vue')['default']
    OptionLink: typeof import('./src/components/interaction/option/option-link.vue')['default']
    RotateCard: typeof import('./src/components/interaction/card/rotate-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabUnderline: typeof import('./src/components/interaction/tab/tab-underline.vue')['default']
    TextUnderline: typeof import('./src/components/interaction/text/text-underline.vue')['default']
    UserAvatar: typeof import('./src/components/user/user-avatar.vue')['default']
    UserAvatarName: typeof import('./src/components/user/user-avatar-name.vue')['default']
    UserName: typeof import('./src/components/user/user-name.vue')['default']
    VerificationCodeInput: typeof import('./src/components/input/verification-code-input.vue')['default']
    WtFillScreen: typeof import('./src/components/layout/wt-fill-screen.vue')['default']
    WtLocale: typeof import('./src/components/wt-locale.vue')['default']
    WtTab: typeof import('./src/components/interaction/tab/wt-tab.vue')['default']
    WtTheme: typeof import('./src/components/wt-theme.vue')['default']
  }
}
